### ISSUE TITLE
TypeError: 'Signal' object is not subscriptable

### ISSUE THREAD

**Issue by nmicauxmellisim** [dioph/periodicity#3]
Hi,
When using `Signal.find_peaks()`, the line `peaks = self[maxima]` returns error `TypeError: 'Signal' object is not subscriptable`.
The context was : 
```
gls = GLS(fmin=fmin, fmax=fmax)
pg = gls(x)
z= pg.val * Signal(y)  # y is an np array
z.find_peaks()
```
N.M.

**Comment by dioph** [comment]
@nmicauxmellisim, this happens because `__getitem__` is only implemented for subclasses of `Signal`; if you want `z` to be the same type as `pg`, you can multiply directly (wihtout using `.val` or `.values`) as such:

```
gls = GLS(fmin=fmin, fmax=fmax)
pg = gls(x)
z = pg * y  # y is an np array
z.find_peaks()
```

I'll be closing this issue, but feel free to ask for any further clarifications.
